const graphdata = [
{
    "nodes": [
        {"id":0, "group": 1},
        {"id":1, "group": 1},
        {"id":2, "group": 1},
        {"id":3, "group": 1},
        {"id":4, "group": 1},
        {"id":5, "group": 1},
        {"id":6, "group": 1}
    ],
    "links": [
        {"source":0, "target":1, "weight": 7},
        {"source":0, "target":3, "weight": 5},
        {"source":1, "target":2, "weight": 8},
        {"source":1, "target":3, "weight": 9},
        {"source":1, "target":4, "weight": 7},
        {"source":2, "target":4, "weight": 5},
        {"source":3, "target":4, "weight": 15},
        {"source":3, "target":5, "weight": 6},
        {"source":4, "target":5, "weight": 8},
        {"source":4, "target":6, "weight": 9},
        {"source":5, "target":6, "weight": 11},
    ]
},
{
    "nodes": [
        {"id":0, "group":0},
        {"id":1, "group":1},
        {"id":2, "group":2},
        {"id":3, "group":3},
        {"id":4, "group":4},
        {"id":5, "group":5},
        {"id":6, "group":6},
        {"id":7, "group":7},
        {"id":8, "group":8},
        {"id":9, "group":9},
        {"id":10, "group":10},
        {"id":11, "group":11},
        {"id":12, "group":12},
        {"id":13, "group":13},
        {"id":14, "group":14},
        {"id":15, "group":15},
        {"id":16, "group":16},
        {"id":17, "group":17},
        {"id":18, "group":18},
        {"id":19, "group":19}
    ],
    "links": [
        {"source":0,"target":1,"value":6},
        {"source":0,"target":4,"value":47},
        {"source":0,"target":8,"value":11},
        {"source":0,"target":16,"value":19},
        {"source":0,"target":19,"value":1},
        {"source":1,"target":3,"value":4},
        {"source":1,"target":7,"value":9},
        {"source":1,"target":10,"value":21},
        {"source":1,"target":13,"value":33},
        {"source":1,"target":16,"value":42},
        {"source":2,"target":3,"value":5},
        {"source":2,"target":5,"value":15},
        {"source":2,"target":12,"value":24},
        {"source":2,"target":13,"value":37},
        {"source":2,"target":17,"value":39},
        {"source":3,"target":4,"value":46},
        {"source":3,"target":11,"value":16},
        {"source":3,"target":18,"value":32},
        {"source":4,"target":5,"value":36},
        {"source":4,"target":7,"value":39},
        {"source":4,"target":11,"value":40},
        {"source":4,"target":15,"value":49},
        {"source":4,"target":18,"value":4},
        {"source":5,"target":6,"value":8},
        {"source":5,"target":11,"value":16},
        {"source":5,"target":12,"value":19},
        {"source":5,"target":16,"value":21},
        {"source":5,"target":18,"value":30},
        {"source":6,"target":7,"value":7},
        {"source":6,"target":9,"value":32},
        {"source":6,"target":13,"value":33},
        {"source":6,"target":16,"value":36},
        {"source":6,"target":17,"value":42},
        {"source":7,"target":8,"value":49},
        {"source":7,"target":11,"value":6},
        {"source":7,"target":15,"value":11},
        {"source":7,"target":16,"value":26},
        {"source":7,"target":17,"value":32},
        {"source":8,"target":9,"value":38},
        {"source":8,"target":12,"value":47},
        {"source":8,"target":14,"value":3},
        {"source":8,"target":18,"value":6},
        {"source":9,"target":10,"value":21},
        {"source":9,"target":14,"value":27},
        {"source":9,"target":19,"value":38},
        {"source":10,"target":13,"value":40},
        {"source":10,"target":15,"value":3},
        {"source":10,"target":19,"value":15},
        {"source":11,"target":14,"value":17},
        {"source":11,"target":17,"value":30},
        {"source":11,"target":19,"value":38},
        {"source":12,"target":15,"value":39},
        {"source":12,"target":17,"value":6},
        {"source":13,"target":18,"value":9},
        {"source":14,"target":15,"value":17},
        {"source":13,"target":19,"value":25},
        {"source":15,"target":16,"value":31},
        {"source":15,"target":19,"value":42},
        {"source":16,"target":18,"value":11},
        {"source":17,"target":19,"value":24}
    ]
},
{
    "nodes": [
        {"id":0, "group":1},
        {"id":1, "group":1},
        {"id":2, "group":1},
        {"id":3, "group":1},
        {"id":4, "group":1},
        {"id":5, "group":1},
        {"id":6, "group":1},
        {"id":7, "group":1},
        {"id":8, "group":1},
        {"id":9, "group":1},
        {"id":10, "group":1},
        {"id":11, "group":1},
        {"id":12, "group":1},
        {"id":13, "group":1},
        {"id":14, "group":1},
        {"id":15, "group":1},
        {"id":16, "group":1},
        {"id":17, "group":1},
        {"id":18, "group":1},
        {"id":19, "group":1}
    ],
    "links": [
        {"source":0,"target":4,"value":47},
        {"source":0,"target":18,"value":12},
        {"source":1,"target":3,"value":4},
        {"source":1,"target":7,"value":9},
        {"source":1,"target":10,"value":21},
        {"source":1,"target":13,"value":33},
        {"source":1,"target":16,"value":42},
        {"source":2,"target":3,"value":5},
        {"source":2,"target":12,"value":24},
        {"source":2,"target":13,"value":37},
        {"source":2,"target":17,"value":39},
        {"source":3,"target":5,"value":27},
        {"source":3,"target":8,"value":17},
        {"source":3,"target":11,"value":16},
        {"source":3,"target":12,"value":5},
        {"source":4,"target":18,"value":4},
        {"source":5,"target":6,"value":8},
        {"source":5,"target":11,"value":16},
        {"source":5,"target":12,"value":19},
        {"source":5,"target":16,"value":21},
        {"source":6,"target":7,"value":7},
        {"source":6,"target":13,"value":33},
        {"source":6,"target":16,"value":36},
        {"source":6,"target":17,"value":42},
        {"source":7,"target":8,"value":49},
        {"source":7,"target":11,"value":6},
        {"source":7,"target":16,"value":26},
        {"source":7,"target":17,"value":32},
        {"source":8,"target":12,"value":47},
        {"source":8,"target":14,"value":3},
        {"source":8,"target":16,"value":46},
        {"source":9,"target":10,"value":21},
        {"source":9,"target":19,"value":38},
        {"source":10,"target":15,"value":3},
        {"source":10,"target":19,"value":15},
        {"source":11,"target":14,"value":17},
        {"source":11,"target":13,"value":32},
        {"source":11,"target":17,"value":30},
        {"source":12,"target":14,"value":26},
        {"source":12,"target":17,"value":6},
        {"source":13,"target":16,"value":35},
        {"source":14,"target":17,"value":2},
        {"source":15,"target":19,"value":42}
    ]
}
];

export default graphdata;
